### ISSUE TITLE
Does not detect user-inserted home instance

### ISSUE THREAD

**Issue by cem-okulmus** [virtulis/substitoot#1]
Gave this a try to get remote-fetching of posts working on the web app. I use "meta.masto.host" as my Mastodon instance, and sadly the extension refuses to activate on that site. Has the extension been actually tested on a wider range of servers? 

My System
Browser: Firefox 115.0.2 (64-bit)
OS: Ubuntu 23.04
Linux Kernel: Linux 6.2.0-25-generic

Extension Version: 0.6.2
Installed via the Mozilla add-on store (https://addons.mozilla.org/en-US/firefox/addon/substitoot/)

Here the settings menu:

![alt text](https://imgpile.com/images/Cdn1K1.png)

And here the extension menu from Firefox, when on a tab with my Mastodon instance:

![alt text](https://imgpile.com/images/CdnIqL.png)
(in case it's now clear, it's shown in a more transparent colour, than the currently active ones (which I blurred). This indicates to me that Substitoot does not seem to recognise this site. ) 

I could also provide logs, but not sure how  that works for web extensions.

**Comment by virtulis** [comment]
Hello,

I just checked and it shows semi-transparent for me as well, despite certainly working, so I don't think that's a good indication. Unfortunately there isn't any other reliable indicator either – I meant to add an address bar icon but never got to it. I'll at least put in a console.log for the next release :)

There are logs in the extension background process. You can find them by going to `about:debugging#/runtime/this-firefox` and clicking "Inspect" under "Extensions / Substitoot".

**Comment by cem-okulmus** [comment]
Oh, you are right, it does actually work. I compared the output with Sengi, a separate app that also supports remote-fetching, and they produce the same list of replies on external posts. Nevermind this issue then. 
Perhaps for UX purposes, it might be a good idea to better communicate to the user when Substitute is active or not.

**Comment by cem-okulmus** [comment]
Oh, you are right, it does actually work. I compared the output with Sengi, a separate app that also supports remote-fetching, and they produce the same list of replies on external posts. Nevermind this issue then.
Perhaps for UX purposes, it might be a good idea to better communicate to the user when Substitute is active or not
